window.__TRANSLATIONS__ = window.__TRANSLATIONS__ || {};
window.__TRANSLATIONS__['es'] = {
  "nav_services": "Servicios",
  "nav_partners": "Socios",
  "nav_about": "Sobre Nosotros",
  "nav_team": "Equipo",
  "nav_contact": "Contacto",
  "nav_region": "Tu región",
  "nav_cta": "Acceder →",
  "hero_title_line1": "Atalou",
  "hero_title_accent": "Microsystem",
  "hero_title_line3": "S.A",
  "hero_sub": "Desde hace más de 20 años, Atalou Microsystem acompaña a las empresas en su transformación digital en todo el mundo.",
  "hero_btn1": "Descubrir servicios",
  "hero_btn2": "Mi país",
  "hero_build": "Construimos.",
  "hero_manage": "Gestionamos.",
  "hero_support": "Soportamos.",
  "hero_contact": "Contáctenos",
  "hero_signage_subtitle": "Transmita sus contenidos",
  "hero_signage_text": "En un clic, transmita sus contenidos multimedia en sus pantallas desde una sola plataforma.",
  "hero_signage_button": "Descubrir SIGNAGE",
  "hero_atapos_subtitle": "SOCIO DE SU CRECIMIENTO",
  "hero_atapos_title": "ATA POS: El futuro de su gestión",
  "hero_atapos_text": "Optimice sus ventas e inventario en tiempo real con nuestra solución estrella. Una interfaz intuitiva diseñada para maximizar su eficiencia comercial.",
  "hero_atapos_button": "Descubrir ATA POS",
  "stat1": "Años de experiencia",
  "stat2": "Soporte activo",
  "scroll_text": "Desplazar",
  "svc_tag": "Nuestras soluciones",
  "svc_title": "Lo que ofrecemos",
  "svc_sub": "Una gama completa de soluciones de TI para acelerar su negocio.",
  "svc_name_1": "ATA POS",
  "svc_desc_1": "Gestión completa de sus ventas, inventario, empleados y crédito en tiempo real.",
  "svc_name_2": "Señalización Digital",
  "svc_desc_2": "Transmita sus contenidos multimedia en todas sus pantallas desde una sola plataforma.",
  "svc_name_3": "Soporte y Mantenimiento",
  "svc_desc_3": "Monitoreo y optimización de redes, alarmas contra incendios y videovigilancia.",
  "svc_name_4": "Soluciones de Red",
  "svc_desc_4": "Telefonía IP, cableado estructurado, conexiones Punto a Punto y multipunto.",
  "svc_name_5": "Servicios Web",
  "svc_desc_5": "Desarrollo a medida de sitios web y aplicaciones móviles. Dominios y alojamiento.",
  "svc_name_6": "Defensa y Vigilancia",
  "svc_desc_6": "Cámaras, seguridad perimetral, gestión biométrica de asistencia y acceso.",
  "svc_name_7": "Soporte de Software",
  "svc_desc_7": "QuickBooks, ACCPAC, CRE, OB POS, protección antivirus y firewall.",
  "svc_desc_8": "Venta de equipos informáticos, geolocalización GPS y soluciones tecnológicas de I+D personalizadas.",
  "svc_name_9": "Nómina",
  "svc_desc_9": "Automatice la gestión de nóminas, vacaciones y declaraciones sociales.",
  "btn_more": "Saber más",
  "about_title": "Nuestra Historia y Filosofía",
  "about_subtitle": "Descubra más de dos décadas de innovación y compromiso tecnológico.",
  "about_description": "Atalou Microsystem es una empresa innovadora especializada en la gestión informática y soluciones empresariales durante más de 20 años. Ayudamos a las empresas a optimizar ventas, proteger datos y mejorar su eficiencia.",
  "about_mission_title": "Nuestra Misión",
  "about_mission_text": "Proporcionar soluciones fiables e innovadoras para mejorar el rendimiento empresarial.",
  "about_vision_title": "Nuestra Visión",
  "about_vision_text": "Convertirnos en el socio preferido de las empresas en su transformación digital y tecnológica.",
  "about_values_title": "Nuestros Valores",
  "about_values_text": "Innovación, fiabilidad, seguridad y compromiso con nuestros clientes y equipos.",
  "services_title": "Soluciones Tecnológicas",
  "services_subtitle": "Descubra nuestras soluciones principales y experiencia en TI.",
  "services_product_badge": "PRODUCTO INNOVADOR",
  "services_product_title": "Sistema ATA POS: Gestión Simplificada, Crecimiento Máximo",
  "services_product_text": "El sistema ATA POS es una solución completa que ayuda a su negocio a gestionar ventas, inventario, empleados y ventas a crédito.",
  "services_product_feature1": "Procesamiento de pagos rápido y seguro",
  "services_product_feature2": "Seguimiento de inventario y fechas de vencimiento",
  "services_product_feature3": "Gestión de empleados y turnos de trabajo",
  "services_product_button": "Ver Más",
  "services_infrastructure_title": "Soporte y Mantenimiento",
  "services_infra_f1": "Instalación, monitoreo y optimización de redes",
  "services_infra_f2": "Sistemas de alarma y detección de incendios",
  "services_infra_f3": "Sistemas de videovigilancia",
  "services_infra_f4": "Mantenimiento de redes informáticas físicas y lógicas",
  "services_infra_f5": "Reparación de sistemas y soporte continuo",
  "services_support_title": "Soporte de Software",
  "services_support_f1": "Soporte técnico (CRE, OB POS, ASI Front Desk)",
  "services_support_f2": "Sistemas contables (QuickBooks, ACCPAC)",
  "services_support_f3": "Protección del PC (Antivirus, Cortafuegos)",
  "services_connectivity_title": "Soluciones de Red",
  "services_network_f1": "Telefonía IP (VoIP)",
  "services_network_f2": "Cableado estructurado (UTP)",
  "services_network_f3": "Conexión Punto a Punto (P2P)",
  "services_network_f4": "Conexión punto a multipunto",
  "services_development_title": "Servicios Web",
  "services_web_f1": "Registro de nombres de dominio",
  "services_web_f2": "Soluciones de alojamiento web",
  "services_web_f3": "Desarrollo a medida de sitios web y aplicaciones móviles",
  "services_security_title": "Defensa y Vigilancia",
  "services_security_f1": "Sistemas de cámaras de seguridad",
  "services_security_f2": "Soluciones de seguridad perimetral",
  "services_security_f3": "Sistemas de gestión de asistencia y biometría",
  "services_products_title": "Otros Servicios",
  "services_other_f1": "Venta de equipos informáticos",
  "services_other_f2": "Sistemas de geolocalización GPS para vehículos y personas",
  "services_other_f3": "Investigación personalizada y I+D de soluciones tecnológicas",
  "services_other_f4": "Sistema de punto de venta ATA (ATA POS)",
  "services_view_more": "Ver Más",
  "part_tag": "Socios",
  "part_title": "Nuestros socios de confianza",
  "part_sub": "Una red de marcas líderes para ofrecerle lo mejor.",
  "part_clients": "Confían en nosotros",
  "partnerships_title": "Nuestros Socios de Confianza",
  "clients_title": "Confían en Nosotros",
  "region_title": "Selecciona tu país",
  "region_sub": "Acceda al sitio web y a las ofertas adaptadas a su mercado local.",
  "region_desc": "Cada mercado tiene sus especificidades. Seleccione su país para acceder al portal dedicado con ofertas, contactos y soporte de su región.",
  "select_placeholder": "— Elige tu país —",
  "btn_go": "Acceder",
  "country_ht": "Haití",
  "country_us": "Estados Unidos",
  "country_do": "República Dominicana",
  "country_jm": " Jamaica",
  "country_carib": " Otro...",
  "label_country": "País",
  "country_placeholder": "— Selecciona tu país —",
  "country_haiti": " Haití",
  "country_usa": " Estados Unidos",
  "country_dom": "República Dominicana",
  "team_title": "El Equipo Detrás de la Innovación",
  "team_ceo_role": "CEO y Fundador",
  "team_director_role": "Directora Ejecutiva",
  "team_tecnic_role": "Director Técnico",
  "team_bs_role": "Soluciones Comerciales",
  "contact_title": "Hablemos de su proyecto",
  "contact_email_title": "Correo Electrónico",
  "contact_phone_title": "Teléfono Principal",
  "footer_rights": "Todos los derechos reservados.",
  "footer_copyright": "Todos los derechos reservados.",
  "demo_title": "Solicitar una Demostración",
  "demo_subtitle": "Descubra cómo Atalou Microsystem puede optimizar sus operaciones.",
  "label_fname": "Nombre",
  "label_lname": "Apellido",
  "label_email": "Correo Electrónico",
  "label_phone": "Número de Teléfono",
  "label_message": "Mensaje",
  "btn_submit_demo": "Enviar Solicitud",
  "demo_sending": "Enviando...",
  "demo_success": "Su solicitud ha sido enviada con éxito.",
  "demo_error": "Ocurrió un error. Por favor intente de nuevo.",
  "pos_page_title": "ATAPOS – Detalles de la solución",
  "pos_nav_home": "Inicio",
  "pos_nav_features": "Características",
  "pos_nav_plans": "Planes",
  "pos_nav_demo": "Demo",
  "pos_badge": "Solución de punto de venta",
  "pos_hero_text": "Una solución POS moderna, fiable y adaptada al mercado local. Gestione sus ventas, inventario y pagos con total facilidad.",
  "pos_slogan": "Vender nunca ha sido tan fácil...",
  "pos_demo_btn": "Solicitar una demo",
  "pos_about_title": "¿Qué es ATAPOS?",
  "pos_about_p1": "ATAPOS es un software de punto de venta adaptado al mercado local, que ofrece a los comerciantes una plataforma simple y confiable para gestionar sus ventas, controlar su inventario y mejorar la experiencia del cliente, incluso en entornos de baja infraestructura.",
  "pos_about_p2": "Integra soluciones de pago adaptadas al mercado local, mejorando la velocidad de las transacciones y la gestión del flujo de caja.",
  "pos_features_title": "¿Por qué elegir ATAPOS?",
  "pos_feature1_title": "Facturación simplificada",
  "pos_feature1_text": "Creación rápida de facturas y seguimiento claro de ventas.",
  "pos_feature2_title": "Gestión de inventario",
  "pos_feature2_text": "Control preciso de entradas y salidas de productos.",
  "pos_feature3_title": "Informes detallados",
  "pos_feature3_text": "Analice su rendimiento en tiempo real.",
  "pos_feature4_title": "Pagos rápidos",
  "pos_feature4_text": "Soluciones adaptadas al mercado local.",
  "pos_feature5_title": "Control remoto",
  "pos_feature5_text": "Acceda a sus datos donde quiera que esté.",
  "pos_feature6_title": "Experiencia del cliente",
  "pos_feature6_text": "Transacciones fluidas y profesionales.",
  "pos_screens_title": "Vista general de la plataforma",
  "pos_plans_title": "Nuestros planes",
  "pos_plan1_name": "Mensual",
  "pos_plan1_price": "$15 / mes",
  "pos_plan1_promo": "1 mes gratis",
  "pos_plan2_name": "Anual",
  "pos_plan2_price": "$12 / mes",
  "pos_plan2_total": "$144",
  "pos_plan2_popular": "El más usado",
  "pos_plan3_name": "Amigos",
  "pos_plan3_price": "$130",
  "pos_plan3_promo": "2 meses gratis",
  "pos_plan_item1": "Tableta o PC",
  "pos_plan_item2": "Impresora",
  "pos_plan_item3": "Conexión a Internet",
  "pos_plan_btn": "Elegir este plan",
  "pos_cta_title": "¿Listo para digitalizar su negocio?",
  "pos_cta_btn": "Ver una demo",
  "pos_popup_subtitle": "Solución de punto de venta",
  "pos_popup_popular": "Popular",
  "pos_payment_title": "Elegir un método de pago",
  "pos_payment_plan": "Plan seleccionado:",
  "pos_payment_card": "Tarjeta bancaria",
  "pos_payment_btn": "Continuar con el pago",
  "support_page_title": "Soporte y Mantenimiento IT",
  "support_page_sub": "Soluciones fiables, seguras y escalables para garantizar la continuidad, el rendimiento y la seguridad de su infraestructura tecnológica.",
  "support_s1_title": "Instalación y optimización de redes",
  "support_s1_text": "Diseñamos e implementamos redes de alto rendimiento y seguras, adaptadas a su actividad. Con monitoreo proactivo, anticipamos fallos y mejoramos la velocidad, estabilidad y disponibilidad de su infraestructura.",
  "support_s2_title": "Alarmas y detección de incendios",
  "support_s2_text": "Protección inteligente de sus instalaciones con sistemas de detección de incendios fiables y conformes a normas. Alertas rápidas, prevención de riesgos y mayor seguridad para sus equipos y equipamiento.",
  "support_s3_title": "Videovigilancia inteligente",
  "support_s3_text": "Instalación de modernos sistemas de videovigilancia con control en tiempo real, acceso remoto y grabación segura para una protección óptima contra intrusiones.",
  "support_s4_title": "Mantenimiento de redes físicas y lógicas",
  "support_s4_text": "Mantenimiento preventivo y correctivo de sus equipos, cableado, servidores y configuraciones de software para garantizar una infraestructura estable, segura y escalable.",
  "support_s5_title": "Reparación y soporte continuo",
  "support_s5_text": "Asistencia técnica reactiva, diagnóstico rápido y soluciones duraderas para minimizar las interrupciones. Nuestro soporte continuo garantiza la continuidad de sus operaciones y la tranquilidad de su empresa.",
  "back_to_services": "Volver a los servicios",
  "logiciel_page_title": "Soporte de Software",
  "logiciel_page_sub": "Garantice la continuidad de sus operaciones con nuestra experiencia en software profesional y protección de sistemas.",
  "logiciel_s1_title": "Soporte técnico",
  "logiciel_s1_text": "Asistencia completa para su software empresarial como CRE, OB POS y ASI Front Desk. Nuestros expertos intervienen rápidamente para resolver sus problemas y garantizar el rendimiento de sus aplicaciones.",
  "logiciel_s2_title": "Sistemas contables",
  "logiciel_s2_text": "Instalación y soporte para QuickBooks, ACCPAC y otros sistemas contables. Optimice sus procesos financieros y gane eficiencia con una guía dedicada.",
  "logiciel_s3_title": "Protección del PC",
  "logiciel_s3_text": "Proteja sus computadoras con antivirus, cortafuegos y soluciones avanzadas de protección. Prevenga ataques y proteja sus datos profesionales contra cualquier amenaza.",
  "reseau_page_title": "Soluciones de Red",
  "reseau_page_sub": "Optimice la conectividad y el rendimiento de su infraestructura de red con nuestras soluciones personalizadas.",
  "reseau_s1_title": "Telefonía IP (VoIP)",
  "reseau_s1_text": "Disfrute de comunicaciones claras y fiables con nuestras soluciones VoIP. Conecte a sus equipos de manera eficiente y reduzca sus costos de telefonía.",
  "reseau_s2_title": "Cableado estructurado (UTP)",
  "reseau_s2_text": "Instalación y organización profesional de su cableado de red para garantizar un rendimiento óptimo, máxima estabilidad y mantenimiento simplificado.",
  "reseau_s3_title": "Conexión Punto a Punto (P2P)",
  "reseau_s3_text": "Establezca enlaces directos seguros entre sus sitios. Garantice una comunicación rápida, estable y fiable para sus datos críticos.",
  "reseau_s4_title": "Conexión Punto a Multipunto",
  "reseau_s4_text": "Conecte un sitio principal a varios sitios remotos con enlaces seguros, ideales para empresas multi-sitio y centralización de datos.",
  "web_page_title": "Servicios Web",
  "web_page_sub": "Desarrolle su presencia digital con soluciones profesionales y personalizadas, del dominio a la aplicación.",
  "web_s1_title": "Registro de nombres de dominio",
  "web_s1_text": "Elija y registre su dominio ideal para su sitio web. Garantizamos un proceso rápido, seguro y adaptado a su marca.",
  "web_s2_title": "Soluciones de alojamiento web",
  "web_s2_text": "Disfrute de un alojamiento fiable y de alto rendimiento para sus sitios y aplicaciones, con copias de seguridad y soporte técnico dedicado.",
  "web_s3_title": "Desarrollo a medida",
  "web_s3_text": "Creación de sitios web y aplicaciones móviles personalizadas, optimizadas para sus necesidades empresariales y usuarios, con diseño moderno y funcionalidades avanzadas.",
  "defense_page_title": "Defensa y Vigilancia",
  "defense_page_sub": "Soluciones de seguridad inteligentes y fiables para proteger sus instalaciones, bienes y colaboradores.",
  "defense_s1_title": "Sistemas de cámaras de seguridad",
  "defense_s1_text": "Instalación de cámaras de alta definición con visión nocturna y acceso remoto. Vigilancia en tiempo real para prevenir intrusiones y proteger sus bienes.",
  "defense_s2_title": "Soluciones de seguridad perimetral",
  "defense_s2_text": "Protección completa de sus edificios y sitios mediante detectores, barreras y alertas automatizadas, garantizando un control total de los accesos.",
  "defense_s3_title": "Sistemas de gestión de asistencia y biometría",
  "defense_s3_text": "Seguimiento preciso de asistencias y accesos seguros mediante tecnologías biométricas. Simplifica la gestión de empleados y refuerza la seguridad.",
  "autres_page_title": "Otros Servicios",
  "autres_page_sub": "Servicios complementarios para satisfacer todas sus necesidades tecnológicas y optimizar sus operaciones.",
  "autres_s1_title": "Venta de equipos informáticos",
  "autres_s1_text": "Computadoras, servidores, impresoras y periféricos de calidad profesional, seleccionados por su rendimiento y fiabilidad.",
  "autres_s2_title": "Sistemas de geolocalización GPS",
  "autres_s2_text": "Seguimiento preciso de vehículos y personas con soluciones GPS de alto rendimiento y fáciles de usar para máxima seguridad.",
  "autres_s3_title": "Investigación y Desarrollo",
  "autres_s3_text": "Creación de soluciones tecnológicas personalizadas para satisfacer sus necesidades únicas y mejorar su eficiencia operativa.",
  "autres_s4_title": "Sistema de punto de venta ATA (ATA POS)",
  "autres_s4_text": "Instalación y configuración de soluciones ATA POS completas para gestionar sus ventas, inventario y clientes de forma eficiente e intuitiva.",
  "sig_page_title": "ATALOU - Señalización Digital",
  "nav_home": "Inicio",
  "sig_nav_what": "¿Qué es?",
  "sig_nav_features": "Beneficios",
  "sig_badge": "Comunicación Visual",
  "sig_hero_text": "Transforme sus pantallas en potentes herramientas de marketing. Difunda el mensaje adecuado, en el momento preciso, desde cualquier lugar.",
  "sig_what_title": "¿Qué es la Señalización Digital?",
  "sig_what_p1": "La Señalización Digital (Digital Signage) es una herramienta de comunicación que permite difundir contenidos multimedia en pantallas instaladas en lugares públicos o puntos de venta.",
  "sig_what_p2": "Es el sustituto moderno de los carteles de papel. Con nuestra plataforma, usted controla a distancia lo que se muestra: promociones, menús, videos o información en tiempo real.",
  "sig_features_title": "¿Por qué adoptar la señalización digital?",
  "sig_f1_title": "Gestión Remota",
  "sig_f1_text": "Actualice sus menús o precios en todas sus pantallas con un solo clic desde su oficina.",
  "sig_f2_title": "Atractivo Visual",
  "sig_f2_text": "Capte un 400% más de atención que un cartel estático gracias a los contenidos animados.",
  "sig_f3_title": "Reducción de Costes",
  "sig_f3_text": "Elimine los gastos de impresión y los retrasos en la entrega de sus materiales publicitarios.",
  "sig_cta_title": "¿Listo para dinamizar sus pantallas?",
  "payroll_page_title": "AtaPayroll – Gestión de nómina | Atalou Microsystem",
  "payroll_nav_home": "Inicio",
  "payroll_nav_about": "Acerca de",
  "payroll_nav_features": "Funcionalidades",
  "payroll_nav_how": "Cómo funciona",
  "payroll_nav_contact": "Contacto",
  "payroll_badge": "Gestión de nómina",
  "payroll_hero_title_1": "AtaPayroll",
  "payroll_hero_title_2": "por Atalou",
  "payroll_hero_text": "Una solución completa para automatizar la gestión de nómina y declaraciones sociales — diseñada para todas las empresas.",
  "payroll_hero_btn_contact": "Contáctenos",
  "payroll_hero_btn_features": "Ver funcionalidades",
  "payroll_stat1": "Conforme",
  "payroll_stat2": "Soporte activo",
  "payroll_stat3": "Multi-moneda",
  "payroll_about_title": "¿Qué es AtaPayroll?",
  "payroll_about_p1": "Atalou Nómina es una solución de gestión de nómina diseñada para empresas que operan en Haití y el Caribe. Automatiza todo el ciclo de remuneración: cálculo de salarios, cotizaciones sociales, gestión de ausencias y generación de recibos de sueldo.",
  "payroll_about_p2": "Con una interfaz intuitiva y cumplimiento de las normativas locales, permite a los equipos de RRHH ahorrar tiempo, reducir errores y garantizar la transparencia en el procesamiento de salarios.",
  "payroll_about_p3": "Se adapta a organizaciones de todos los tamaños: PYMES, grandes empresas y ONG.",
  "payroll_features_title": "¿Por qué elegir AtaPayroll?",
  "payroll_feature1_title": "Cálculo automático de nómina",
  "payroll_feature1_text": "Salarios base, horas extra, bonificaciones y deducciones calculados automáticamente en cada ciclo de nómina.",
  "payroll_feature2_title": "Recibos de sueldo instantáneos",
  "payroll_feature2_text": "Generación y distribución digital de recibos de sueldo con un clic, accesibles en cualquier momento por los empleados.",
  "payroll_feature3_title": "Gestión de vacaciones y ausencias",
  "payroll_feature3_text": "Seguimiento en tiempo real de vacaciones, bajas por enfermedad, maternidad y ausencias con impacto automático en la nómina.",
  "payroll_feature4_title": "Cumplimiento normativo",
  "payroll_feature4_text": "Cumplimiento de las obligaciones legales haitianas: cotizaciones ONA, OFATMA, impuesto sobre la renta y declaraciones sociales.",
  "payroll_feature5_title": "Multi-moneda",
  "payroll_feature5_text": "Gestión simultánea en todas las monedas según los contratos de sus empleados.",
  "payroll_feature6_title": "Informes y análisis de RRHH",
  "payroll_feature6_text": "Paneles de control e informes detallados sobre la masa salarial, costos por departamento y tendencias de RRHH.",
  "payroll_feature7_title": "Gestión multi-empleados",
  "payroll_feature7_text": "Gestione decenas o cientos de empleados con perfiles individualizados, categorías y estructuras salariales diferentes.",
  "payroll_feature8_title": "Seguridad y confidencialidad",
  "payroll_feature8_text": "Datos cifrados, acceso por roles y registros de auditoría para garantizar la confidencialidad de la información salarial.",
  "payroll_feature9_title": "Integración sencilla",
  "payroll_feature9_text": "Compatible con sus herramientas existentes: QuickBooks, ACCPAC, reloj biométrico y ATAPOS.",
  "payroll_how_title": "¿Cómo funciona?",
  "payroll_how_sub": "Un proceso simple y estructurado para garantizar una nómina precisa en cada ciclo.",
  "payroll_step1_title": "Configuración de empleados",
  "payroll_step1_text": "Cree los perfiles de sus empleados: contrato, salario base, beneficios, cotizaciones y departamento.",
  "payroll_step2_title": "Recopilación de datos del mes",
  "payroll_step2_text": "El sistema integra automáticamente las ausencias, horas extra y bonificaciones del período.",
  "payroll_step3_title": "Cálculo y validación",
  "payroll_step3_text": "La nómina se calcula automáticamente. El responsable de RRHH valida o ajusta antes de finalizar.",
  "payroll_step4_title": "Distribución de recibos",
  "payroll_step4_text": "Los recibos de sueldo se generan y envían digitalmente a cada empleado en segundos.",
  "payroll_step5_title": "Informes y archivado",
  "payroll_step5_text": "Todos los ciclos de nómina quedan archivados y accesibles para auditorías, declaraciones fiscales o análisis de RRHH.",
  "payroll_cta_title": "¿Listo para simplificar su gestión de nómina?",
  "payroll_cta_sub": "Contacte a nuestro equipo para una demostración personalizada y descubra cómo Atalou Nómina puede transformar su departamento de RRHH.",
  "payroll_cta_btn": "Solicitar una demostración"
};