window.__TRANSLATIONS__ = window.__TRANSLATIONS__ || {};
window.__TRANSLATIONS__['fr'] = {
  "nav_services": "Services",
  "nav_partners": "Partenaires",
  "nav_about": "À Propos",
  "nav_team": "Équipe",
  "nav_contact": "Contact",
  "nav_region": "Votre région",
  "nav_cta": "Accéder →",
  "hero_title_line1": "Atalou",
  "hero_title_accent": "Microsystem",
  "hero_title_line3": "S.A",
  "hero_sub": "Depuis plus de 20 ans, Atalou Microsystem accompagne les entreprises dans leur transformation digitale — partout dans le monde.",
  "hero_btn1": "Découvrir nos services",
  "hero_btn2": "Mon pays",
  "hero_build": "Nous construisons.",
  "hero_manage": "Nous gérons.",
  "hero_support": "Nous supportons.",
  "hero_contact": "Contactez-nous",
  "hero_signage_subtitle": "Diffusez vos contenus",
  "hero_signage_text": "En un clic, diffusez vos contenus multimédias sur vos écrans à partir d'une seule plateforme.",
  "hero_signage_button": "Découvrir SIGNAGE",
  "hero_atapos_subtitle": "PARTENAIRE DE VOTRE CROISSANCE",
  "hero_atapos_title": "ATA POS : Le futur de votre gestion",
  "hero_atapos_text": "Optimisez vos ventes et votre inventaire en temps réel avec notre solution phare. Une interface intuitive conçue pour maximiser votre efficacité commerciale.",
  "hero_atapos_button": "Découvrir ATA POS",
  "stat1": "Années d'expérience",
  "stat2": "Support actif",
  "scroll_text": "Défiler",
  "svc_tag": "Nos solutions",
  "svc_title": "Ce que nous proposons",
  "svc_sub": "Une gamme complète de solutions IT pour accélérer votre activité.",
  "svc_name_1": "ATA POS",
  "svc_desc_1": "Gestion complète de vos ventes, inventaire, employés et crédit en temps réel.",
  "svc_name_2": "Signage Digital",
  "svc_desc_2": "Diffusez vos contenus multimédias sur tous vos écrans depuis une seule plateforme.",
  "svc_name_3": "Support & Maintenance",
  "svc_desc_3": "Surveillance et optimisation des réseaux, alarmes incendie, vidéosurveillance.",
  "svc_name_4": "Solutions Réseau",
  "svc_desc_4": "Téléphonie IP, câblage structuré, connexions Point-à-Point et multipoint.",
  "svc_name_5": "Services Web",
  "svc_desc_5": "Développement sur mesure de sites et d'applications mobiles. Domaines & hébergement.",
  "svc_name_6": "Défense & Surveillance",
  "svc_desc_6": "Caméras, périmétrique, gestion biométrique de présence et accès.",
  "svc_name_7": "Support Logiciel",
  "svc_desc_7": "QuickBooks, ACCPAC, CRE, OB POS, protection antivirus et pare-feu.",
  "svc_desc_8": "Vente d'équipements informatiques, géolocalisation GPS et R&D de solutions technologiques sur mesure.",
  "svc_name_9": "Payroll",
  "svc_desc_9": "Automatisez la gestion de votre paie, des congés et des déclarations sociales.",
  "btn_more": "En savoir plus",
  "about_title": "Notre Histoire & Philosophie",
  "about_subtitle": "Découvrez plus de deux décennies d'innovation et d'engagement technologique.",
  "about_description": "Atalou Microsystem est une entreprise innovante spécialisée dans la gestion informatique et les solutions business depuis plus de 20 ans. Nous aidons les entreprises à optimiser leurs ventes, sécuriser leurs données et améliorer leur efficacité.",
  "about_mission_title": "Notre Mission",
  "about_mission_text": "Fournir des solutions fiables et innovantes pour améliorer la performance des entreprises.",
  "about_vision_title": "Notre Vision",
  "about_vision_text": "Devenir le partenaire privilégié des entreprises dans leur transformation digitale et technologique.",
  "about_values_title": "Nos Valeurs",
  "about_values_text": "Innovation, fiabilité, sécurité et engagement envers nos clients et nos équipes.",
  "services_title": "Solutions Technologiques",
  "services_subtitle": "Découvrez nos solutions phares et notre expertise IT.",
  "services_product_badge": "PRODUIT INNOVANT",
  "services_product_title": "ATA POS System : Gestion Simplifiée, Croissance Maximale",
  "services_product_text": "Le système ATA POS est une solution complète qui aide votre commerce à gérer les ventes, l'inventaire, les employés, et offre des ventes à crédit.",
  "services_product_feature1": "Traitement des paiements rapide et sécurisé",
  "services_product_feature2": "Suivi d'inventaire et des dates d'expiration",
  "services_product_feature3": "Gestion des employés et des quarts de travail",
  "services_product_button": "Voir Plus",
  "services_infrastructure_title": "Support et Maintenance",
  "services_infra_f1": "Mise en place, surveillance et optimisation des réseaux",
  "services_infra_f2": "Systèmes d'alarme et de détection incendie",
  "services_infra_f3": "Systèmes de vidéosurveillance",
  "services_infra_f4": "Maintenance des réseaux informatiques physiques et logiques",
  "services_infra_f5": "Réparation des systèmes et support continu",
  "services_support_title": "Support Logiciel",
  "services_support_f1": "Support technique (CRE, OB POS, ASI Front Desk)",
  "services_support_f2": "Systèmes comptables (QuickBooks, ACCPAC)",
  "services_support_f3": "Protection PC (Antivirus, Pare-feu)",
  "services_connectivity_title": "Solutions Réseau",
  "services_network_f1": "Téléphonie IP (VoIP)",
  "services_network_f2": "Câblage structuré (UTP)",
  "services_network_f3": "Connexion Point-à-Point (P2P)",
  "services_network_f4": "Connexion point à multipoint",
  "services_development_title": "Services Web",
  "services_web_f1": "Enregistrement de noms de domaine",
  "services_web_f2": "Solutions d'hébergement web",
  "services_web_f3": "Développement sur mesure de sites web et d'applications mobiles",
  "services_security_title": "Défense et Surveillance",
  "services_security_f1": "Systèmes de caméras de sécurité",
  "services_security_f2": "Solutions de sécurité périmétrique",
  "services_security_f3": "Systèmes de gestion de présence et biométrique",
  "services_products_title": "Autres Services",
  "services_other_f1": "Vente d'équipements informatiques",
  "services_other_f2": "Systèmes de géolocalisation GPS pour véhicules et personnes",
  "services_other_f3": "Recherche personnalisée et R&D de solutions technologiques",
  "services_other_f4": "Système de point de vente ATA (ATA POS)",
  "services_view_more": "Voir Plus",
  "part_tag": "Partenaires",
  "part_title": "Nos partenaires de confiance",
  "part_sub": "Un réseau de marques de premier plan pour vous offrir le meilleur.",
  "part_clients": "Ils nous font confiance",
  "partnerships_title": "Nos Partenaires de Confiance",
  "clients_title": "Ils Nous Font Confiance",
  "region_title": "Sélectionnez votre pays",
  "region_sub": "Accédez au site et aux offres adaptées à votre marché local.",
  "region_desc": "Chaque marché a ses spécificités. Sélectionnez votre pays pour accéder au portail dédié avec les offres, les contacts et le support de votre région.",
  "select_placeholder": "— Choisir votre pays —",
  "btn_go": "Accéder",
  "country_ht": "Haïti",
  "country_us": "États-Unis",
  "country_do": "République Dominicaine",
  "country_jm": " Jamaïque",
  "country_carib": "Autre...",
  "label_country": "Pays",
  "country_placeholder": "— Sélectionner votre pays —",
  "country_haiti": "Haïti",
  "country_usa": " États-Unis",
  "country_dom": "République Dominicaine",
  "team_title": "L'Équipe Derrière l'Innovation",
  "team_ceo_role": "CEO & Fondateur",
  "team_director_role": "Directrice Exécutive",
  "team_tecnic_role": "Directeur Technique",
  "team_bs_role": "Solution Commerciale",
  "contact_title": "Discutons de votre projet",
  "contact_email_title": "Adresse E-mail",
  "contact_phone_title": "Téléphone Principal",
  "footer_rights": "Tous droits réservés.",
  "footer_copyright": "Tous droits réservés.",
  "demo_title": "Demander une Démonstration",
  "demo_subtitle": "Découvrez comment Atalou Microsystem peut optimiser vos opérations.",
  "label_fname": "Prénom",
  "label_lname": "Nom",
  "label_email": "Adresse E-mail",
  "label_phone": "Numéro de Téléphone",
  "label_message": "Message",
  "btn_submit_demo": "Envoyer la Demande",
  "demo_sending": "Envoi en cours...",
  "demo_success": "Votre demande a été envoyée avec succès.",
  "demo_error": "Une erreur est survenue. Veuillez réessayer.",
  "pos_page_title": "ATAPOS – Détails de la solution",
  "pos_nav_home": "Accueil",
  "pos_nav_features": "Caractéristiques",
  "pos_nav_plans": "Plans",
  "pos_nav_demo": "Démo",
  "pos_badge": "Solution de point de vente",
  "pos_hero_text": "Une solution POS moderne, fiable et adaptée au marché haïtien. Gérez vos ventes, vos stocks et vos paiements en toute simplicité.",
  "pos_slogan": "Vendre n'a jamais été aussi simple...",
  "pos_demo_btn": "Demander une démo",
  "pos_about_title": "Qu'est-ce que ATAPOS ?",
  "pos_about_p1": "ATAPOS est un logiciel de point de vente adapté au marché Haïtien, offrant aux commerçants une plateforme simple et fiable pour gérer leurs ventes, contrôler leurs stocks et améliorer l'expérience client, même dans des environnements à faibles infrastructures.",
  "pos_about_p2": "Il intègre des solutions de paiement adaptées au marché local, améliorant ainsi la rapidité des transactions et la gestion des flux de trésorerie.",
  "pos_features_title": "Pourquoi choisir ATAPOS ?",
  "pos_feature1_title": "Facturation simplifiée",
  "pos_feature1_text": "Création rapide de factures et suivi clair des ventes.",
  "pos_feature2_title": "Gestion des stocks",
  "pos_feature2_text": "Contrôle précis des entrées et sorties de produits.",
  "pos_feature3_title": "Rapports détaillés",
  "pos_feature3_text": "Analysez vos performances en temps réel.",
  "pos_feature4_title": "Paiements rapides",
  "pos_feature4_text": "Solutions adaptées au marché local.",
  "pos_feature5_title": "Contrôle à distance",
  "pos_feature5_text": "Accédez à vos données où que vous soyez.",
  "pos_feature6_title": "Expérience client",
  "pos_feature6_text": "Transactions fluides et professionnelles.",
  "pos_screens_title": "Aperçu de la plateforme",
  "pos_plans_title": "Nos plans",
  "pos_plan1_name": "Mensuel",
  "pos_plan1_price": "$15 / mois",
  "pos_plan1_promo": "1 mois gratuit",
  "pos_plan2_name": "Annuel",
  "pos_plan2_price": "$12 / mois",
  "pos_plan2_total": "$144",
  "pos_plan2_popular": "Le plus utilisé",
  "pos_plan3_name": "Amis",
  "pos_plan3_price": "$130",
  "pos_plan3_promo": "2 mois gratuits",
  "pos_plan_item1": "Tablette ou PC",
  "pos_plan_item2": "Printer",
  "pos_plan_item3": "Connexion Internet",
  "pos_plan_btn": "Choisir ce plan",
  "pos_cta_title": "Prêt à digitaliser votre commerce ?",
  "pos_cta_btn": "Visualiser une démo",
  "pos_popup_subtitle": "Solution de point de vente",
  "pos_popup_popular": "Populaire",
  "pos_payment_title": "Choisir un mode de paiement",
  "pos_payment_plan": "Plan sélectionné :",
  "pos_payment_card": "Carte bancaire",
  "pos_payment_btn": "Continuer le paiement",
  "support_page_title": "Support & Maintenance IT",
  "support_page_sub": "Des solutions fiables, sécurisées et évolutives pour assurer la continuité, la performance et la sécurité de votre infrastructure technologique.",
  "support_s1_title": "Mise en place & optimisation des réseaux",
  "support_s1_text": "Nous concevons et déployons des réseaux performants et sécurisés, adaptés à votre activité. Grâce à une surveillance proactive, nous anticipons les pannes et améliorons la vitesse, la stabilité et la disponibilité de votre infrastructure.",
  "support_s2_title": "Alarmes & détection incendie",
  "support_s2_text": "Protection intelligente de vos locaux grâce à des systèmes de détection incendie fiables et conformes aux normes. Alertes rapides, prévention des risques et sécurité renforcée pour vos équipes et vos équipements.",
  "support_s3_title": "Vidéosurveillance intelligente",
  "support_s3_text": "Installation de systèmes de vidéosurveillance modernes permettant un contrôle en temps réel, un accès à distance et un enregistrement sécurisé pour une protection optimale contre les intrusions.",
  "support_s4_title": "Maintenance réseaux physiques & logiques",
  "support_s4_text": "Maintenance préventive et corrective de vos équipements, câblages, serveurs et configurations logicielles afin d'assurer une infrastructure stable, sécurisée et évolutive.",
  "support_s5_title": "Réparation & support continu",
  "support_s5_text": "Assistance technique réactive, diagnostic rapide et solutions durables pour limiter les interruptions. Notre support continu garantit la continuité de vos opérations et la tranquillité de votre entreprise.",
  "back_to_services": "Retour aux services",
  "logiciel_page_title": "Support Logiciel",
  "logiciel_page_sub": "Assurez la continuité de vos opérations grâce à notre expertise sur vos logiciels professionnels et la protection de vos systèmes.",
  "logiciel_s1_title": "Support technique",
  "logiciel_s1_text": "Assistance complète pour vos logiciels métiers tels que CRE, OB POS et ASI Front Desk. Nos experts interviennent rapidement pour résoudre vos problèmes et garantir la performance de vos applications.",
  "logiciel_s2_title": "Systèmes comptables",
  "logiciel_s2_text": "Mise en place et support pour QuickBooks, ACCPAC et autres systèmes comptables. Optimisez vos processus financiers et gagnez en efficacité avec un accompagnement dédié.",
  "logiciel_s3_title": "Protection PC",
  "logiciel_s3_text": "Sécurisez vos ordinateurs avec des antivirus, pare-feu et solutions avancées de protection. Prévenez les attaques et protégez vos données professionnelles contre toute menace.",
  "reseau_page_title": "Solutions Réseau",
  "reseau_page_sub": "Optimisez la connectivité et la performance de votre infrastructure réseau avec nos solutions sur mesure.",
  "reseau_s1_title": "Téléphonie IP (VoIP)",
  "reseau_s1_text": "Profitez de communications claires et fiables grâce à nos solutions VoIP. Connectez vos équipes efficacement et réduisez vos coûts de téléphonie.",
  "reseau_s2_title": "Câblage structuré (UTP)",
  "reseau_s2_text": "Installation et organisation professionnelle de votre câblage réseau pour garantir une performance optimale, une stabilité maximale et une maintenance simplifiée.",
  "reseau_s3_title": "Connexion Point-à-Point (P2P)",
  "reseau_s3_text": "Établissez des liaisons directes sécurisées entre vos sites. Assurez une communication rapide, stable et fiable pour vos données critiques.",
  "reseau_s4_title": "Connexion Point-à-Multipoint",
  "reseau_s4_text": "Connectez un site principal à plusieurs sites distants avec des liaisons sécurisées, idéales pour les entreprises multi-sites et la centralisation des données.",
  "web_page_title": "Services Web",
  "web_page_sub": "Développez votre présence digitale avec des solutions professionnelles et personnalisées, du domaine à l'application.",
  "web_s1_title": "Enregistrement de noms de domaine",
  "web_s1_text": "Choisissez et enregistrez votre domaine idéal pour votre site web. Nous assurons un processus rapide, sécurisé et adapté à votre marque.",
  "web_s2_title": "Solutions d'hébergement web",
  "web_s2_text": "Profitez d'un hébergement fiable et performant pour vos sites et applications, avec des sauvegardes sécurisées et un support technique dédié.",
  "web_s3_title": "Développement sur mesure",
  "web_s3_text": "Création de sites web et applications mobiles personnalisées, optimisées pour vos besoins métiers et vos utilisateurs, avec design moderne et fonctionnalités avancées.",
  "defense_page_title": "Défense & Surveillance",
  "defense_page_sub": "Des solutions de sécurité intelligentes et fiables pour protéger vos locaux, vos biens et vos collaborateurs.",
  "defense_s1_title": "Systèmes de caméras de sécurité",
  "defense_s1_text": "Installation de caméras haute définition avec vision nocturne et accès à distance. Surveillance en temps réel pour prévenir les intrusions et protéger vos biens.",
  "defense_s2_title": "Solutions de sécurité périmétrique",
  "defense_s2_text": "Protection complète de vos bâtiments et sites grâce à des détecteurs, barrières et alertes automatisées, assurant un contrôle total des accès.",
  "defense_s3_title": "Systèmes de gestion de présence et biométrique",
  "defense_s3_text": "Suivi précis des présences et accès sécurisés grâce aux technologies biométriques. Simplifie la gestion des employés tout en renforçant la sécurité.",
  "autres_page_title": "Autres Services",
  "autres_page_sub": "Des services complémentaires pour répondre à tous vos besoins technologiques et optimiser vos opérations.",
  "autres_s1_title": "Vente d'équipements informatiques",
  "autres_s1_text": "Ordinateurs, serveurs, imprimantes et périphériques de qualité professionnelle, sélectionnés pour la performance et la fiabilité.",
  "autres_s2_title": "Systèmes de géolocalisation GPS",
  "autres_s2_text": "Suivi précis de véhicules et de personnes grâce à des solutions GPS performantes et faciles à utiliser pour une sécurité maximale.",
  "autres_s3_title": "Recherche & Développement",
  "autres_s3_text": "Création de solutions technologiques personnalisées pour répondre à vos besoins uniques et améliorer votre efficacité opérationnelle.",
  "autres_s4_title": "Système de point de vente ATA (ATA POS)",
  "autres_s4_text": "Installation et configuration de solutions ATA POS complètes pour gérer vos ventes, stocks et clients de manière efficace et intuitive.",
  "sig_page_title": "ATALOU – Digital Signage",
  "nav_home": "Accueil",
  "sig_nav_what": "C'est quoi ?",
  "sig_nav_features": "Bénéfices",
  "sig_badge": "Affichage Dynamique",
  "sig_hero_text": "Transformez vos écrans en outils de vente dynamiques. Diffusez vos publicités, menus et annonces en temps réel, partout dans le monde.",
  "sig_what_title": "Qu'est-ce que le Digital Signage ?",
  "sig_what_p1": "L'affichage dynamique (Digital Signage) est une solution de communication qui permet de diffuser du contenu multimédia sur des écrans numériques (TV, tablettes, moniteurs).",
  "sig_what_p2": "Contrairement aux affiches papier, vous pouvez modifier vos messages en un clic depuis une interface web. C'est l'outil idéal pour les restaurants (menu boards), les magasins (promotions) et les entreprises (communication interne).",
  "sig_features_title": "Pourquoi choisir notre solution ?",
  "sig_f1_title": "Contrôle à distance",
  "sig_f1_text": "Pilotez tous vos écrans à travers le pays depuis un simple navigateur web.",
  "sig_f2_title": "Multi-format",
  "sig_f2_text": "Diffusez des vidéos 4K, des images, des flux RSS ou même des pages web en direct.",
  "sig_f3_title": "Planification intelligente",
  "sig_f3_text": "Programmez vos contenus par heure, jour ou événement spécial automatiquement.",
  "sig_cta_title": "Prêt à moderniser votre communication ?",
  "payroll_page_title": "Payroll – Gestion de la paie | Atalou Microsystem",
  "payroll_nav_home": "Accueil",
  "payroll_nav_about": "À propos",
  "payroll_nav_features": "Fonctionnalités",
  "payroll_nav_how": "Fonctionnement",
  "payroll_nav_contact": "Contact",
  "payroll_badge": "Gestion de la paie",
  "payroll_hero_title_1": "AtaPayroll",
  "payroll_hero_title_2": "par Atalou",
  "payroll_hero_text": "Une solution complète pour automatiser la gestion de votre paie, des congés et des déclarations sociales — adaptée à toutes entreprises et partout.",
  "payroll_hero_btn_contact": "Nous contacter",
  "payroll_hero_btn_features": "Voir les fonctionnalités",
  "payroll_stat1": "Conforme",
  "payroll_stat2": "Support actif",
  "payroll_stat3": "Multi-devises",
  "payroll_about_title": "Qu'est-ce que AtaPayroll ?",
  "payroll_about_p1": "Payroll Atalou est une solution de gestion de la paie conçue pour les entreprises opérant en Haïti et dans les Caraïbes. Elle automatise l'ensemble du cycle de rémunération : calcul des salaires, cotisations sociales, gestion des absences et génération des bulletins de paie.",
  "payroll_about_p2": "Grâce à une interface intuitive et une conformité aux réglementations locales, elle permet aux équipes RH de gagner du temps, de réduire les erreurs et d'assurer la transparence des traitements salariaux.",
  "payroll_about_p3": "Elle s'adapte aux structures de toutes tailles PME, grandes entreprises, ONG.",
  "payroll_features_title": "Pourquoi choisir AtaPayroll ?",
  "payroll_feature1_title": "Calcul automatique de la paie",
  "payroll_feature1_text": "Salaires de base, heures supplémentaires, primes et retenues calculés automatiquement à chaque cycle de paie.",
  "payroll_feature2_title": "Bulletins de paie instantanés",
  "payroll_feature2_text": "Génération et distribution numérique des bulletins de paie en un clic, accessibles à tout moment par les employés.",
  "payroll_feature3_title": "Gestion des congés & absences",
  "payroll_feature3_text": "Suivi en temps réel des congés annuels, maladie, maternité et absences avec impact automatique sur la paie.",
  "payroll_feature4_title": "Conformité réglementaire",
  "payroll_feature4_text": "Respect des obligations légales haïtiennes : cotisations ONA, OFATMA, impôt sur le revenu et déclarations sociales.",
  "payroll_feature5_title": "Multi-devises",
  "payroll_feature5_text": "Gestion simultanée dans toutes les devises, selon les contrats de vos employés.",
  "payroll_feature6_title": "Rapports & analyses RH",
  "payroll_feature6_text": "Tableaux de bord et rapports détaillés sur la masse salariale, les coûts par département et les tendances RH.",
  "payroll_feature7_title": "Gestion multi-employés",
  "payroll_feature7_text": "Gérez des dizaines ou des centaines d'employés avec des profils individualisés, des grades et des structures de paie différentes.",
  "payroll_feature8_title": "Sécurité & confidentialité",
  "payroll_feature8_text": "Données chiffrées, accès par rôles et journaux d'audit pour garantir la confidentialité des informations salariales.",
  "payroll_feature9_title": "Intégration facile",
  "payroll_feature9_text": "Compatible avec vos outils existants : QuickBooks, ACCPAC, pointeuse biométrique et ATAPOS.",
  "payroll_how_title": "Comment ça fonctionne ?",
  "payroll_how_sub": "Un processus simple et structuré pour garantir une paie précise à chaque cycle.",
  "payroll_step1_title": "Configuration des employés",
  "payroll_step1_text": "Créez les profils de vos employés : contrat, salaire de base, avantages, cotisations et département.",
  "payroll_step2_title": "Collecte des données du mois",
  "payroll_step2_text": "Le système intègre automatiquement les absences, heures supplémentaires et primes de la période.",
  "payroll_step3_title": "Calcul & validation",
  "payroll_step3_text": "La paie est calculée automatiquement. Le responsable RH valide ou ajuste avant finalisation.",
  "payroll_step4_title": "Distribution des bulletins",
  "payroll_step4_text": "Les bulletins de paie sont générés et envoyés numériquement à chaque employé en quelques secondes.",
  "payroll_step5_title": "Rapports & archivage",
  "payroll_step5_text": "Tous les cycles de paie sont archivés et accessibles pour audit, déclarations fiscales ou analyses RH.",
  "payroll_cta_title": "Prêt à simplifier votre gestion de la paie ?",
  "payroll_cta_sub": "Contactez notre équipe pour une démonstration personnalisée et découvrez comment Payroll Atalou peut transformer votre département RH.",
  "payroll_cta_btn": "Demander une démonstration"
};